# -*- coding: utf-8 -*-
"""Lego_Analysis_for_Course_(start).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bNGl-ZjLBLbiGrrVE-2v7HlxZ_XUDd5k

# Introduction

Today we'll dive deep into a dataset all about LEGO. From the dataset we can ask whole bunch of interesting questions about the history of the LEGO company, their product offering, and which LEGO set ultimately rules them all:

<ul type="square">
<li>What is the most enormous LEGO set ever created and how many parts did it have?</li>

<li>How did the LEGO company start out? In which year were the first LEGO sets released and how many sets did the company sell when it first launched?</li>

<li>Which LEGO theme has the most sets? Is it one of LEGO's own themes like Ninjago or a theme they licensed liked Harry Potter or Marvel Superheroes?</li>

<li>When did the LEGO company really expand its product offering? Can we spot a change in the company strategy based on how many themes and sets did it released year-on-year?</li>

<li>Did LEGO sets grow in size and complexity over time? Do older LEGO
sets tend to have more or fewer parts than newer sets?</li>
</ul>

**Data Source**

[Rebrickable](https://rebrickable.com/downloads/) has compiled data on all the LEGO pieces in existence. I recommend you use download the .csv files provided in this lesson.

### Import Statements

<img src="https://i.imgur.com/49FNOHj.jpg">
"""

import pandas as pd

df = pd.read_csv('./data/colors.csv')

df.head()

df.groupby('name').count()

df.shape

df.nunique()

df.groupby('is_trans').count()

print (df.loc[df['is_trans'] == 't'])





print (df.loc[df['name'].str.contains('Trans')])













print(df)

df2 = pd.read_csv('./data/sets.csv')

df2.head()

df2.sort_values('year').head(6)

df2.sort_values('year').groupby('year').sum()

df2.sort_values('num_parts').tail(5)

sets_by_year = df2.sort_values('year').groupby('year').count().filter(items=['set_num'])

sets_by_year.head()

import matplotlib.pyplot as plt

sets_by_year.plot()

sets_by_year[:-2].plot(legend='')

theme_by_year = df2.groupby('year').agg({'theme_id':pd.Series.nunique})

theme_by_year.rename(columns= {'theme_id':'nr_themes'}, inplace=True)

theme_by_year.head()

theme_by_year[:-2].plot(legend='')

ax1 = plt.gca() # get current axes
ax2 = ax1.twinx()
ax1.plot(sets_by_year.index[:-2], sets_by_year.set_num[:-2], color='g')
ax2.plot(theme_by_year.index[:-2],theme_by_year.nr_themes[:-2],'b')
ax1.set_xlabel('year')
ax1.set_ylabel('Number of sets', color='green')
ax2.set_ylabel('Number of themes', color='blue')

df2.sort_values('year').groupby('year').agg('mean').filter(items=['num_parts']).head()

avg_set_part_per_year = df2.sort_values('year').groupby('year').agg('mean').filter(items=['num_parts'])



avg_set_part_per_year.head()



plt.scatter(avg_set_part_per_year.index[:-2],avg_set_part_per_year.num_parts[:-2])

set_theme_count = df2['theme_id'].value_counts()

set_theme_count[:5]



"""<img src="https://i.imgur.com/Sg4lcjx.png">"""

themes = pd.read_csv('./data/themes.csv')

themes.head()

themes.name.str.contains('Star Wars').head()

themes.name.str.contains('Star Wars').tail()

print(themes[themes['name'] == 'Star Wars'])

print(df2[df2['theme_id'] == 18])



print(df2.loc[df2['theme_id'].eq(18) |df2['theme_id'].eq(158) |df2['theme_id'].eq(209) |df2['theme_id'].eq(261)].sort_values('theme_id'))

themes = themes.rename(columns={'id': 'theme_id'})





themes.head()

merged_df = pd.merge(df2, themes, on='theme_id')

merged_df.head()

print(merged_df.loc[merged_df['theme_id'].eq(18)])

plt.figure(figsize=(14,8))
plt.xticks(fontsize=14, rotation=45)
plt.yticks(fontsize=14)
plt.ylabel('Nr of Sets', fontsize=14)
plt.xlabel('Theme Name', fontsize=14)

plt.bar(merged_df.name_x[:10], merged_df.num_parts[:10])































































print(df2['theme_id'].str.contains('18'))





























































































































"""# Data Exploration

**Challenge**: How many different colours does the LEGO company produce? Read the colors.csv file in the data folder and find the total number of unique colours. Try using the [.nunique() method](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.nunique.html?highlight=nunique#pandas.DataFrame.nunique) to accomplish this.
"""







"""**Challenge**: Find the number of transparent colours where <code>is_trans == 't'</code> versus the number of opaque colours where <code>is_trans == 'f'</code>. See if you can accomplish this in two different ways."""





"""**Challenge**: Change this into an h3 section heading: Understanding LEGO Themes vs. LEGO Sets

Walk into a LEGO store and you will see their products organised by theme. Their themes include Star Wars, Batman, Harry Potter and many more.

**Challenge**: Display this image: https://i.imgur.com/aKcwkSx.png

A lego set is a particular box of LEGO or product. Therefore, a single theme typically has many different sets.

**Challenge**: Display this image https://i.imgur.com/whB1olq.png

The <code>sets.csv</code> data contains a list of sets over the years and the number of parts that each of these sets contained.

**Challenge**: Read the sets.csv data and take a look at the first and last couple of rows.
"""







"""**Challenge**: In which year were the first LEGO sets released and what were these sets called?"""



"""**Challenge**: How many different sets did LEGO sell in their first year? How many types of LEGO products were on offer in the year the company started?"""



"""**Challenge**: Find the top 5 LEGO sets with the most number of parts."""



"""**Challenge**: Use <code>.groupby()</code> and <code>.count()</code> to show the number of LEGO sets released year-on-year. How do the number of sets released in 1955 compare to the number of sets released in 2019?"""





"""**Challenge**: Show the number of LEGO releases on a line chart using Matplotlib. <br>
<br>
Note that the .csv file is from late 2020, so to plot the full calendar years, you will have to exclude some data from your chart. Can you use the slicing techniques covered in Day 21 to avoid plotting the last two years? The same syntax will work on Pandas DataFrames.
"""





"""### Aggregate Data with the Python .agg() Function

Let's work out the number of different themes shipped by year. This means we have to count the number of unique theme_ids per calendar year.
"""





"""**Challenge**: Plot the number of themes released by year on a line chart. Only include the full calendar years (i.e., exclude 2020 and 2021)."""



"""### Line Charts with Two Seperate Axes"""



"""**Challenge**: Use the <code>.groupby()</code> and <code>.agg()</code> function together to figure out the average number of parts per set. How many parts did the average LEGO set released in 1954 compared to say, 2017?"""





"""### Scatter Plots in Matplotlib

**Challenge**: Has the size and complexity of LEGO sets increased over time based on the number of parts? Plot the average number of parts over time using a Matplotlib scatter plot. See if you can use the [scatter plot documentation](https://matplotlib.org/3.1.0/api/_as_gen/matplotlib.pyplot.scatter.html) before I show you the solution. Do you spot a trend in the chart?
"""



"""### Number of Sets per LEGO Theme

LEGO has licensed many hit franchises from Harry Potter to Marvel Super Heros to many others. But which theme has the largest number of individual sets?
"""



"""**Challenge** Use what you know about HTML markup and tags to display the database schema: https://i.imgur.com/Sg4lcjx.png

### Database Schemas, Foreign Keys and Merging DataFrames

The themes.csv file has the actual theme names. The sets .csv has <code>theme_ids</code> which link to the <code>id</code> column in the themes.csv.

**Challenge**: Explore the themes.csv. How is it structured? Search for the name 'Star Wars'. How many <code>id</code>s correspond to this name in the themes.csv? Now use these <code>id</code>s and find the corresponding the sets in the sets.csv (Hint: you'll need to look for matches in the <code>theme_id</code> column)
"""











"""### Merging (i.e., Combining) DataFrames based on a Key

"""





